"""add_ai_permissions_and_consolidate_revive_v2

Revision ID: 07e4c065d440
Revises: a3c55b6b9914
Create Date: 2026-01-18 11:59:03.354454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07e4c065d440'
down_revision = 'a3c55b6b9914'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual fix: Drop constraint before dropping referenced table
    op.drop_constraint('knowledge_sync_history_source_id_fkey', 'knowledge_sync_history', type_='foreignkey')
    op.create_table('ai_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('pillar', sa.String(length=20), nullable=False),
    sa.Column('tool_category', sa.String(length=50), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'pillar', 'tool_category', 'tool_name', name='uq_ai_permission_role_tool')
    )


    op.create_table('ai_action_confirmations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_details', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_tool_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('tool_category', sa.String(length=50), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('result_status', sa.String(length=20), nullable=True),
    sa.Column('permission_required', sa.String(length=100), nullable=True),
    sa.Column('permission_granted', sa.Boolean(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['ai_messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('safety_level', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_knowledge_sources_enabled', table_name='knowledge_sources')
    op.drop_index('ix_knowledge_sources_source_type', table_name='knowledge_sources')
    op.drop_index('ix_knowledge_sources_status', table_name='knowledge_sources')
    op.drop_index('ix_knowledge_sources_tenant_id', table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index('ix_ai_helper_config_config_key', table_name='ai_helper_config')
    op.drop_index('ix_ai_helper_config_config_type', table_name='ai_helper_config')
    op.drop_table('ai_helper_config')
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('agent_sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('agent_sessions', 'auto_approve',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('agent_sessions', 'max_steps',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('agent_sessions', 'current_step_number',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('agent_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('agent_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('agent_sessions', 'agent_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('agent_sessions', 'auto_iterate',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('agent_sessions', 'max_auto_iterations',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('ix_agent_sessions_chat_session_id', table_name='agent_sessions')
    op.drop_index('ix_agent_sessions_current_phase', table_name='agent_sessions')
    op.drop_index('ix_agent_sessions_status', table_name='agent_sessions')
    op.drop_index('ix_agent_sessions_user_id', table_name='agent_sessions')
    op.drop_constraint('agent_sessions_chat_session_id_fkey', 'agent_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'agent_sessions', 'ai_sessions', ['chat_session_id'], ['id'])
    op.drop_column('agent_sessions', 'current_phase')
    op.drop_column('agent_sessions', 'phase_history')
    op.drop_column('agent_sessions', 'plan_step_index')
    op.drop_column('agent_sessions', 'task_list')
    op.drop_column('agent_sessions', 'current_plan')
    op.drop_column('agent_sessions', 'autonomy_level')
    op.drop_column('agent_sessions', 'investigation_tool_count')
    op.alter_column('agent_steps', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('agent_steps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('agent_steps', 'iteration_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('ix_agent_steps_agent_session_id', table_name='agent_steps')
    op.drop_index('ix_agent_steps_ivipa_phase', table_name='agent_steps')
    op.drop_index('ix_agent_steps_step_number', table_name='agent_steps')
    op.drop_column('agent_steps', 'tool_output')
    op.drop_column('agent_steps', 'output_analysis')
    op.drop_column('agent_steps', 'thinking')
    op.drop_column('agent_steps', 'tool_input')
    op.drop_column('agent_steps', 'ivipa_phase')
    op.drop_column('agent_steps', 'tool_name')
    op.alter_column('agent_tasks', 'auto_iterate',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('agent_tasks', 'max_iterations',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_ai_feedback_created_at', table_name='ai_feedback')
    op.drop_index('idx_ai_feedback_feedback_type', table_name='ai_feedback')
    op.drop_index('idx_ai_feedback_runbook_id', table_name='ai_feedback')
    op.drop_index('idx_ai_feedback_target_type', table_name='ai_feedback')
    op.drop_index('idx_ai_feedback_user_id', table_name='ai_feedback')
    op.drop_index('ix_ai_feedback_created_at', table_name='ai_feedback')
    op.drop_index('ix_ai_feedback_message_id', table_name='ai_feedback')
    op.drop_index('ix_ai_feedback_runbook_id', table_name='ai_feedback')
    op.drop_index('ix_ai_feedback_session_id', table_name='ai_feedback')
    op.drop_index('ix_ai_feedback_user_id', table_name='ai_feedback')
    op.drop_constraint('ai_feedback_runbook_id_fkey', 'ai_feedback', type_='foreignkey')
    op.drop_constraint('ai_feedback_user_id_fkey', 'ai_feedback', type_='foreignkey')
    op.drop_column('ai_feedback', 'response_text')
    op.drop_column('ai_feedback', 'feedback_type')
    op.drop_column('ai_feedback', 'target_type')
    op.drop_column('ai_feedback', 'query_text')
    op.alter_column('ai_helper_audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.alter_column('ai_helper_audit_logs', 'correlation_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('ai_helper_audit_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_ai_audit_llm_request', table_name='ai_helper_audit_logs', postgresql_using='gin')
    op.drop_index('idx_ai_audit_page_context', table_name='ai_helper_audit_logs', postgresql_using='gin')
    op.drop_index('ix_ai_helper_audit_logs_action_blocked', table_name='ai_helper_audit_logs')
    op.drop_index('ix_ai_helper_audit_logs_ai_suggested_action', table_name='ai_helper_audit_logs')
    op.drop_index('ix_ai_helper_audit_logs_correlation_id', table_name='ai_helper_audit_logs')
    op.drop_index('ix_ai_helper_audit_logs_executed', table_name='ai_helper_audit_logs')
    op.drop_index('ix_ai_helper_audit_logs_execution_result', table_name='ai_helper_audit_logs')
    op.drop_index('ix_ai_helper_audit_logs_is_error', table_name='ai_helper_audit_logs')
    op.drop_index('ix_ai_helper_audit_logs_session_id', table_name='ai_helper_audit_logs')
    op.drop_index('ix_ai_helper_audit_logs_timestamp', table_name='ai_helper_audit_logs')
    op.drop_index('ix_ai_helper_audit_logs_user_action', table_name='ai_helper_audit_logs')
    op.drop_index('ix_ai_helper_audit_logs_user_id', table_name='ai_helper_audit_logs')
    op.drop_constraint('ai_helper_audit_logs_user_id_fkey', 'ai_helper_audit_logs', type_='foreignkey')
    op.drop_constraint('ai_helper_audit_logs_session_id_fkey', 'ai_helper_audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'ai_helper_audit_logs', 'ai_helper_sessions', ['session_id'], ['id'])
    op.drop_column('ai_helper_audit_logs', 'execution_details')
    op.drop_column('ai_helper_audit_logs', 'context_assembly_ms')
    op.drop_column('ai_helper_audit_logs', 'user_feedback')
    op.drop_column('ai_helper_audit_logs', 'user_modifications')
    op.drop_column('ai_helper_audit_logs', 'code_files_referenced')
    op.drop_column('ai_helper_audit_logs', 'user_query')
    op.drop_column('ai_helper_audit_logs', 'llm_tokens_output')
    op.drop_column('ai_helper_audit_logs', 'page_context')
    op.drop_column('ai_helper_audit_logs', 'llm_provider')
    op.drop_column('ai_helper_audit_logs', 'user_agent')
    op.drop_column('ai_helper_audit_logs', 'total_duration_ms')
    op.drop_column('ai_helper_audit_logs', 'llm_model')
    op.drop_column('ai_helper_audit_logs', 'block_reason')
    op.drop_column('ai_helper_audit_logs', 'llm_request')
    op.drop_column('ai_helper_audit_logs', 'knowledge_chunks_used')
    op.drop_column('ai_helper_audit_logs', 'error_type')
    op.drop_column('ai_helper_audit_logs', 'llm_response')
    op.drop_column('ai_helper_audit_logs', 'user_action_timestamp')
    op.drop_column('ai_helper_audit_logs', 'ai_reasoning')
    op.drop_column('ai_helper_audit_logs', 'ip_address')
    op.drop_column('ai_helper_audit_logs', 'request_id')
    op.drop_column('ai_helper_audit_logs', 'permissions_granted')
    op.drop_column('ai_helper_audit_logs', 'rag_search_time_ms')
    op.drop_column('ai_helper_audit_logs', 'error_stack_trace')
    op.drop_column('ai_helper_audit_logs', 'username')
    op.drop_column('ai_helper_audit_logs', 'llm_tokens_input')
    op.drop_column('ai_helper_audit_logs', 'llm_cost_usd')
    op.drop_column('ai_helper_audit_logs', 'user_feedback_comment')
    op.drop_column('ai_helper_audit_logs', 'ai_action_details')
    op.drop_column('ai_helper_audit_logs', 'error_message')
    op.drop_column('ai_helper_audit_logs', 'permissions_required')
    op.drop_column('ai_helper_audit_logs', 'execution_timestamp')
    op.drop_column('ai_helper_audit_logs', 'affected_resources')
    op.drop_column('ai_helper_audit_logs', 'ai_confidence_score')
    op.drop_column('ai_helper_audit_logs', 'knowledge_sources_used')
    op.drop_column('ai_helper_audit_logs', 'llm_latency_ms')
    op.drop_column('ai_helper_audit_logs', 'llm_tokens_total')
    op.drop_column('ai_helper_audit_logs', 'code_functions_referenced')
    op.alter_column('ai_helper_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ai_helper_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.alter_column('ai_helper_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_helper_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_index('ix_ai_helper_sessions_last_activity_at', table_name='ai_helper_sessions')
    op.drop_index('ix_ai_helper_sessions_status', table_name='ai_helper_sessions')
    op.drop_index('ix_ai_helper_sessions_user_id', table_name='ai_helper_sessions')
    op.drop_constraint('ai_helper_sessions_user_id_fkey', 'ai_helper_sessions', type_='foreignkey')
    op.drop_column('ai_helper_sessions', 'context')
    op.drop_column('ai_helper_sessions', 'duration_seconds')
    op.drop_column('ai_helper_sessions', 'ended_at')
    op.add_column('ai_messages', sa.Column('tool_calls', sa.JSON(), nullable=True))
    op.add_column('ai_messages', sa.Column('tool_call_id', sa.String(length=100), nullable=True))
    op.add_column('ai_messages', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('ai_sessions', sa.Column('pillar', sa.String(length=20), nullable=False, server_default='revive'))
    op.add_column('ai_sessions', sa.Column('revive_mode', sa.String(length=20), nullable=True))
    op.add_column('ai_sessions', sa.Column('context_type', sa.String(length=50), nullable=True))
    op.add_column('ai_sessions', sa.Column('context_id', sa.UUID(), nullable=True))
    op.add_column('ai_sessions', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ai_sessions', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ai_sessions', sa.Column('message_count', sa.Integer(), nullable=True))
    op.execute("DELETE FROM ai_sessions WHERE user_id IS NULL")
    op.alter_column('ai_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('ai_sessions', 'updated_at')
    op.alter_column('application_knowledge_configs', 'git_branch',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('application_knowledge_configs', 'git_auth_type',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('application_knowledge_configs', 'sync_docs',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('application_knowledge_configs', 'sync_code',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('application_knowledge_configs', 'doc_patterns',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('application_knowledge_configs', 'exclude_patterns',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('application_knowledge_configs', 'auto_sync_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('application_knowledge_configs', 'sync_interval_hours',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('application_knowledge_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('incident_metrics', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('incident_metrics', 'incident_detected',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('knowledge_sync_history', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.alter_column('knowledge_sync_history', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('knowledge_sync_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('knowledge_sync_history', 'source_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_knowledge_sync_history_source_id', table_name='knowledge_sync_history')
    # op.drop_constraint('knowledge_sync_history_source_id_fkey', 'knowledge_sync_history', type_='foreignkey') # Moved to top
    op.drop_column('knowledge_sync_history', 'previous_commit_sha')
    op.drop_column('knowledge_sync_history', 'completed_at')
    op.drop_column('knowledge_sync_history', 'error_details')
    op.drop_column('knowledge_sync_history', 'new_commit_sha')
    op.drop_column('knowledge_sync_history', 'error_message')
    op.drop_column('knowledge_sync_history', 'duration_ms')
    op.alter_column('runbook_clicks', 'runbook_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_runbook_clicks_clicked_at', table_name='runbook_clicks')
    op.drop_index('idx_runbook_clicks_runbook_id', table_name='runbook_clicks')
    op.drop_index('idx_runbook_clicks_source', table_name='runbook_clicks')
    op.drop_index('idx_runbook_clicks_user_id', table_name='runbook_clicks')
    op.drop_index('ix_runbook_clicks_clicked_at', table_name='runbook_clicks')
    op.drop_index('ix_runbook_clicks_runbook_id', table_name='runbook_clicks')
    op.drop_index('ix_runbook_clicks_session_id', table_name='runbook_clicks')
    op.drop_index('ix_runbook_clicks_user_id', table_name='runbook_clicks')
    op.drop_constraint('runbook_clicks_user_id_fkey', 'runbook_clicks', type_='foreignkey')
    op.drop_constraint('runbook_clicks_runbook_id_fkey', 'runbook_clicks', type_='foreignkey')
    op.drop_column('runbook_clicks', 'context_json')
    op.drop_column('runbook_clicks', 'confidence_shown')
    op.drop_column('runbook_clicks', 'query_text')
    op.drop_column('runbook_clicks', 'rank_shown')
    op.drop_column('runbooks', 'embedding')
    op.alter_column('solution_outcomes', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('solution_outcomes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_solution_outcomes_embedding', table_name='solution_outcomes', postgresql_ops={'problem_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('users', sa.Column('ai_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_preferences')
    op.create_index('idx_solution_outcomes_embedding', 'solution_outcomes', ['problem_embedding'], unique=False, postgresql_ops={'problem_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('solution_outcomes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('solution_outcomes', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('runbooks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    op.add_column('runbook_clicks', sa.Column('rank_shown', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('runbook_clicks', sa.Column('query_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('runbook_clicks', sa.Column('confidence_shown', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('runbook_clicks', sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_foreign_key('runbook_clicks_runbook_id_fkey', 'runbook_clicks', 'runbooks', ['runbook_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('runbook_clicks_user_id_fkey', 'runbook_clicks', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_runbook_clicks_user_id', 'runbook_clicks', ['user_id'], unique=False)
    op.create_index('ix_runbook_clicks_session_id', 'runbook_clicks', ['session_id'], unique=False)
    op.create_index('ix_runbook_clicks_runbook_id', 'runbook_clicks', ['runbook_id'], unique=False)
    op.create_index('ix_runbook_clicks_clicked_at', 'runbook_clicks', ['clicked_at'], unique=False)
    op.create_index('idx_runbook_clicks_user_id', 'runbook_clicks', ['user_id'], unique=False)
    op.create_index('idx_runbook_clicks_source', 'runbook_clicks', ['source'], unique=False)
    op.create_index('idx_runbook_clicks_runbook_id', 'runbook_clicks', ['runbook_id'], unique=False)
    op.create_index('idx_runbook_clicks_clicked_at', 'runbook_clicks', ['clicked_at'], unique=False)
    op.alter_column('runbook_clicks', 'runbook_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('knowledge_sync_history', sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('knowledge_sync_history', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('knowledge_sync_history', sa.Column('new_commit_sha', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('knowledge_sync_history', sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('knowledge_sync_history', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('knowledge_sync_history', sa.Column('previous_commit_sha', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_foreign_key('knowledge_sync_history_source_id_fkey', 'knowledge_sync_history', 'knowledge_sources', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_knowledge_sync_history_source_id', 'knowledge_sync_history', ['source_id'], unique=False)
    op.alter_column('knowledge_sync_history', 'source_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('knowledge_sync_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('knowledge_sync_history', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('knowledge_sync_history', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('incident_metrics', 'incident_detected',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('incident_metrics', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('application_knowledge_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('application_knowledge_configs', 'sync_interval_hours',
               existing_type=sa.INTEGER(),
               server_default=sa.text('24'),
               existing_nullable=True)
    op.alter_column('application_knowledge_configs', 'auto_sync_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('application_knowledge_configs', 'exclude_patterns',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text('\'["**/node_modules/**", "**/.git/**"]\'::json'),
               existing_nullable=True)
    op.alter_column('application_knowledge_configs', 'doc_patterns',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text('\'["*.md", "docs/**/*"]\'::json'),
               existing_nullable=True)
    op.alter_column('application_knowledge_configs', 'sync_code',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('application_knowledge_configs', 'sync_docs',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('application_knowledge_configs', 'git_auth_type',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'none'::character varying"),
               existing_nullable=True)
    op.alter_column('application_knowledge_configs', 'git_branch',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'main'::character varying"),
               existing_nullable=True)
    op.add_column('ai_sessions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('ai_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('ai_sessions', 'message_count')
    op.drop_column('ai_sessions', 'ended_at')
    op.drop_column('ai_sessions', 'started_at')
    op.drop_column('ai_sessions', 'context_id')
    op.drop_column('ai_sessions', 'context_type')
    op.drop_column('ai_sessions', 'revive_mode')
    op.drop_column('ai_sessions', 'pillar')
    op.drop_column('ai_messages', 'tokens_used')
    op.drop_column('ai_messages', 'tool_call_id')
    op.drop_column('ai_messages', 'tool_calls')
    op.add_column('ai_helper_sessions', sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('ai_helper_sessions', sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_helper_sessions', sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_foreign_key('ai_helper_sessions_user_id_fkey', 'ai_helper_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_ai_helper_sessions_user_id', 'ai_helper_sessions', ['user_id'], unique=False)
    op.create_index('ix_ai_helper_sessions_status', 'ai_helper_sessions', ['status'], unique=False)
    op.create_index('ix_ai_helper_sessions_last_activity_at', 'ai_helper_sessions', ['last_activity_at'], unique=False)
    op.alter_column('ai_helper_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('ai_helper_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('ai_helper_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('ai_helper_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('ai_helper_audit_logs', sa.Column('code_functions_referenced', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('llm_tokens_total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('llm_latency_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('knowledge_sources_used', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('ai_confidence_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('affected_resources', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('execution_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('permissions_required', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('ai_action_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('user_feedback_comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('llm_cost_usd', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('llm_tokens_input', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('ai_helper_audit_logs', sa.Column('error_stack_trace', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('rag_search_time_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('permissions_granted', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('request_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('ai_reasoning', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('user_action_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('llm_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('error_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('knowledge_chunks_used', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('llm_request', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('block_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('llm_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('total_duration_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('llm_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('page_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('llm_tokens_output', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('user_query', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('ai_helper_audit_logs', sa.Column('code_files_referenced', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('user_modifications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('user_feedback', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('context_assembly_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_helper_audit_logs', sa.Column('execution_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ai_helper_audit_logs', type_='foreignkey')
    op.create_foreign_key('ai_helper_audit_logs_session_id_fkey', 'ai_helper_audit_logs', 'ai_helper_sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('ai_helper_audit_logs_user_id_fkey', 'ai_helper_audit_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_ai_helper_audit_logs_user_id', 'ai_helper_audit_logs', ['user_id'], unique=False)
    op.create_index('ix_ai_helper_audit_logs_user_action', 'ai_helper_audit_logs', ['user_action'], unique=False)
    op.create_index('ix_ai_helper_audit_logs_timestamp', 'ai_helper_audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_ai_helper_audit_logs_session_id', 'ai_helper_audit_logs', ['session_id'], unique=False)
    op.create_index('ix_ai_helper_audit_logs_is_error', 'ai_helper_audit_logs', ['is_error'], unique=False)
    op.create_index('ix_ai_helper_audit_logs_execution_result', 'ai_helper_audit_logs', ['execution_result'], unique=False)
    op.create_index('ix_ai_helper_audit_logs_executed', 'ai_helper_audit_logs', ['executed'], unique=False)
    op.create_index('ix_ai_helper_audit_logs_correlation_id', 'ai_helper_audit_logs', ['correlation_id'], unique=False)
    op.create_index('ix_ai_helper_audit_logs_ai_suggested_action', 'ai_helper_audit_logs', ['ai_suggested_action'], unique=False)
    op.create_index('ix_ai_helper_audit_logs_action_blocked', 'ai_helper_audit_logs', ['action_blocked'], unique=False)
    op.create_index('idx_ai_audit_page_context', 'ai_helper_audit_logs', ['page_context'], unique=False, postgresql_using='gin')
    op.create_index('idx_ai_audit_llm_request', 'ai_helper_audit_logs', ['llm_request'], unique=False, postgresql_using='gin')
    op.alter_column('ai_helper_audit_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ai_helper_audit_logs', 'correlation_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('ai_helper_audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.add_column('ai_feedback', sa.Column('query_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_feedback', sa.Column('target_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('ai_feedback', sa.Column('feedback_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('ai_feedback', sa.Column('response_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('ai_feedback_user_id_fkey', 'ai_feedback', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('ai_feedback_runbook_id_fkey', 'ai_feedback', 'runbooks', ['runbook_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_ai_feedback_user_id', 'ai_feedback', ['user_id'], unique=False)
    op.create_index('ix_ai_feedback_session_id', 'ai_feedback', ['session_id'], unique=False)
    op.create_index('ix_ai_feedback_runbook_id', 'ai_feedback', ['runbook_id'], unique=False)
    op.create_index('ix_ai_feedback_message_id', 'ai_feedback', ['message_id'], unique=False)
    op.create_index('ix_ai_feedback_created_at', 'ai_feedback', ['created_at'], unique=False)
    op.create_index('idx_ai_feedback_user_id', 'ai_feedback', ['user_id'], unique=False)
    op.create_index('idx_ai_feedback_target_type', 'ai_feedback', ['target_type'], unique=False)
    op.create_index('idx_ai_feedback_runbook_id', 'ai_feedback', ['runbook_id'], unique=False)
    op.create_index('idx_ai_feedback_feedback_type', 'ai_feedback', ['feedback_type'], unique=False)
    op.create_index('idx_ai_feedback_created_at', 'ai_feedback', ['created_at'], unique=False)
    op.alter_column('agent_tasks', 'max_iterations',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=True)
    op.alter_column('agent_tasks', 'auto_iterate',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.add_column('agent_steps', sa.Column('tool_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('agent_steps', sa.Column('ivipa_phase', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('agent_steps', sa.Column('tool_input', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agent_steps', sa.Column('thinking', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('agent_steps', sa.Column('output_analysis', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('agent_steps', sa.Column('tool_output', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('ix_agent_steps_step_number', 'agent_steps', ['agent_session_id', 'step_number'], unique=False)
    op.create_index('ix_agent_steps_ivipa_phase', 'agent_steps', ['ivipa_phase'], unique=False)
    op.create_index('ix_agent_steps_agent_session_id', 'agent_steps', ['agent_session_id'], unique=False)
    op.alter_column('agent_steps', 'iteration_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('agent_steps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('agent_steps', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.add_column('agent_sessions', sa.Column('investigation_tool_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('agent_sessions', sa.Column('autonomy_level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.add_column('agent_sessions', sa.Column('current_plan', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agent_sessions', sa.Column('task_list', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agent_sessions', sa.Column('plan_step_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('agent_sessions', sa.Column('phase_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agent_sessions', sa.Column('current_phase', sa.VARCHAR(length=20), server_default=sa.text("'identify'::character varying"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'agent_sessions', type_='foreignkey')
    op.create_foreign_key('agent_sessions_chat_session_id_fkey', 'agent_sessions', 'ai_sessions', ['chat_session_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_agent_sessions_user_id', 'agent_sessions', ['user_id'], unique=False)
    op.create_index('ix_agent_sessions_status', 'agent_sessions', ['status'], unique=False)
    op.create_index('ix_agent_sessions_current_phase', 'agent_sessions', ['current_phase'], unique=False)
    op.create_index('ix_agent_sessions_chat_session_id', 'agent_sessions', ['chat_session_id'], unique=False)
    op.alter_column('agent_sessions', 'max_auto_iterations',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=True)
    op.alter_column('agent_sessions', 'auto_iterate',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('agent_sessions', 'agent_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'local'::character varying"),
               existing_nullable=True)
    op.alter_column('agent_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('agent_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('agent_sessions', 'current_step_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('agent_sessions', 'max_steps',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               existing_nullable=True)
    op.alter_column('agent_sessions', 'auto_approve',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('agent_sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'idle'::character varying"),
               existing_nullable=True)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('ai_helper_config',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('config_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('config_value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('config_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_encrypted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint("config_type::text = ANY (ARRAY['system'::character varying, 'user'::character varying, 'tenant'::character varying]::text[])", name='ck_ai_config_type'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='ai_helper_config_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='ai_helper_config_updated_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='ai_helper_config_pkey')
    )
    op.create_index('ix_ai_helper_config_config_type', 'ai_helper_config', ['config_type'], unique=False)
    op.create_index('ix_ai_helper_config_config_key', 'ai_helper_config', ['config_key'], unique=True)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sync_schedule', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('auto_sync', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_commit_sha', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('last_sync_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_sync_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sync_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_documents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_chunks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("source_type::text = ANY (ARRAY['git_docs'::character varying, 'git_code'::character varying, 'local_files'::character varying, 'external_api'::character varying]::text[])", name='ck_knowledge_sources_type'),
    sa.CheckConstraint("status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'error'::character varying, 'archived'::character varying]::text[])", name='ck_knowledge_sources_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='knowledge_sources_created_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='knowledge_sources_pkey')
    )
    op.create_index('ix_knowledge_sources_tenant_id', 'knowledge_sources', ['tenant_id'], unique=False)
    op.create_index('ix_knowledge_sources_status', 'knowledge_sources', ['status'], unique=False)
    op.create_index('ix_knowledge_sources_source_type', 'knowledge_sources', ['source_type'], unique=False)
    op.create_index('ix_knowledge_sources_enabled', 'knowledge_sources', ['enabled'], unique=False)
    op.drop_table('action_proposals')
    op.drop_table('ai_tool_executions')
    op.drop_table('ai_action_confirmations')
    op.drop_table('ai_permissions')
    # ### end Alembic commands ###
