"""sync_schema_drift

Revision ID: 65c6b0133982
Revises: 043_add_ai_feedback
Create Date: 2026-01-07 23:34:18.582490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65c6b0133982'
down_revision = '4e706f82cee5'
branch_labels = None
depends_on = None


def drop_index_if_exists(index_name, table_name, **kw):
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = inspector.get_indexes(table_name)
    if any(i['name'] == index_name for i in indexes):
        op.drop_index(index_name, table_name=table_name, **kw)
    else:
        print(f"Skipping drop: Index {index_name} on {table_name} not found")

def create_index_if_not_exists(index_name, table_name, columns, **kw):
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = inspector.get_indexes(table_name)
    # Handle op.f() or simple strings. If op.f(), name might be raw (unlikely to match inspector output directly if naming convention differs?)
    # Inspector returns actual DB names.
    # op.f(...) usually resolves to the specific name based on convention.
    # We should assume index_name passed here is the target name.
    # But op.f returns a quoted string or object? check.
    # Actually, let's just use the string name.
    
    # Check if index exists
    if any(i['name'] == index_name for i in indexes):
        print(f"Skipping create: Index {index_name} on {table_name} already exists")
        return

    op.create_index(index_name, table_name, columns, **kw)

def drop_constraint_if_exists(constraint_name, table_name, type_=None, **kw):
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    if constraint_name is None:
        print(f"Skipping drop: Constraint name is None on {table_name}")
        return

    exists = False
    if type_ == 'unique' or type_ is None:
        try:
            cons = inspector.get_unique_constraints(table_name)
            if any(c['name'] == constraint_name for c in cons):
                exists = True
        except: pass
    
    if not exists and (type_ == 'foreignkey' or type_ is None):
        try:
            cons = inspector.get_foreign_keys(table_name)
            if any(c['name'] == constraint_name for c in cons):
                exists = True
        except: pass
        
    if exists:
        op.drop_constraint(constraint_name, table_name=table_name, type_=type_, **kw)
    else:
        print(f"Skipping drop: Constraint {constraint_name} on {table_name} not found")

def drop_column_if_exists(table_name, column_name, **kw):
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = inspector.get_columns(table_name)
    if any(c['name'] == column_name for c in columns):
        op.drop_column(table_name, column_name, **kw)
    else:
        print(f"Skipping drop: Column {column_name} on {table_name} not found")

def add_column_if_not_exists(table_name, column, **kw):
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    column_name = column.name
    columns = inspector.get_columns(table_name)
    if any(c['name'] == column_name for c in columns):
        print(f"Skipping add: Column {column_name} on {table_name} already exists")
        return
    op.add_column(table_name, column, **kw)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_feedback', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    drop_index_if_exists('idx_ai_feedback_message_id', table_name='ai_feedback')
    drop_index_if_exists('idx_ai_feedback_session_id', table_name='ai_feedback')
    create_index_if_not_exists(op.f('ix_ai_feedback_created_at'), 'ai_feedback', ['created_at'], unique=False)
    create_index_if_not_exists(op.f('ix_ai_feedback_message_id'), 'ai_feedback', ['message_id'], unique=False)
    create_index_if_not_exists(op.f('ix_ai_feedback_runbook_id'), 'ai_feedback', ['runbook_id'], unique=False)
    create_index_if_not_exists(op.f('ix_ai_feedback_session_id'), 'ai_feedback', ['session_id'], unique=False)
    create_index_if_not_exists(op.f('ix_ai_feedback_user_id'), 'ai_feedback', ['user_id'], unique=False)
    op.alter_column('ai_helper_audit_logs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_helper_audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_helper_audit_logs', 'executed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_helper_audit_logs', 'action_blocked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_helper_audit_logs', 'permission_checked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_helper_audit_logs', 'is_error',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    drop_index_if_exists('idx_ai_audit_action', table_name='ai_helper_audit_logs')
    drop_index_if_exists('idx_ai_audit_blocked', table_name='ai_helper_audit_logs', postgresql_where='(action_blocked = true)')
    drop_index_if_exists('idx_ai_audit_correlation', table_name='ai_helper_audit_logs')
    drop_index_if_exists('idx_ai_audit_error', table_name='ai_helper_audit_logs', postgresql_where='(is_error = true)')
    drop_index_if_exists('idx_ai_audit_executed', table_name='ai_helper_audit_logs')
    drop_index_if_exists('idx_ai_audit_session', table_name='ai_helper_audit_logs')
    drop_index_if_exists('idx_ai_audit_timestamp', table_name='ai_helper_audit_logs')
    drop_index_if_exists('idx_ai_audit_user_action', table_name='ai_helper_audit_logs')
    drop_index_if_exists('idx_ai_audit_user_time', table_name='ai_helper_audit_logs')
    create_index_if_not_exists(op.f('ix_ai_helper_audit_logs_action_blocked'), 'ai_helper_audit_logs', ['action_blocked'], unique=False)
    create_index_if_not_exists(op.f('ix_ai_helper_audit_logs_ai_suggested_action'), 'ai_helper_audit_logs', ['ai_suggested_action'], unique=False)
    create_index_if_not_exists(op.f('ix_ai_helper_audit_logs_correlation_id'), 'ai_helper_audit_logs', ['correlation_id'], unique=False)
    create_index_if_not_exists(op.f('ix_ai_helper_audit_logs_executed'), 'ai_helper_audit_logs', ['executed'], unique=False)
    create_index_if_not_exists(op.f('ix_ai_helper_audit_logs_execution_result'), 'ai_helper_audit_logs', ['execution_result'], unique=False)
    create_index_if_not_exists(op.f('ix_ai_helper_audit_logs_is_error'), 'ai_helper_audit_logs', ['is_error'], unique=False)
    create_index_if_not_exists(op.f('ix_ai_helper_audit_logs_session_id'), 'ai_helper_audit_logs', ['session_id'], unique=False)
    create_index_if_not_exists(op.f('ix_ai_helper_audit_logs_timestamp'), 'ai_helper_audit_logs', ['timestamp'], unique=False)
    create_index_if_not_exists(op.f('ix_ai_helper_audit_logs_user_action'), 'ai_helper_audit_logs', ['user_action'], unique=False)
    create_index_if_not_exists(op.f('ix_ai_helper_audit_logs_user_id'), 'ai_helper_audit_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'ai_helper_audit_logs', 'ai_helper_sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.alter_column('ai_helper_config', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_helper_config', 'config_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_helper_config', 'is_encrypted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_helper_config', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_helper_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_helper_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    drop_constraint_if_exists('ai_helper_config_config_key_key', 'ai_helper_config', type_='unique')
    drop_index_if_exists('idx_ai_config_key', table_name='ai_helper_config')
    drop_index_if_exists('idx_ai_config_type', table_name='ai_helper_config')
    create_index_if_not_exists(op.f('ix_ai_helper_config_config_key'), 'ai_helper_config', ['config_key'], unique=True)
    create_index_if_not_exists(op.f('ix_ai_helper_config_config_type'), 'ai_helper_config', ['config_type'], unique=False)
    op.alter_column('ai_helper_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_helper_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_helper_sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_helper_sessions', 'total_queries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_helper_sessions', 'total_tokens_used',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_helper_sessions', 'total_cost_usd',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_helper_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_helper_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_helper_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    drop_index_if_exists('idx_ai_sessions_activity', table_name='ai_helper_sessions')
    drop_index_if_exists('idx_ai_sessions_status', table_name='ai_helper_sessions')
    drop_index_if_exists('idx_ai_sessions_user', table_name='ai_helper_sessions')
    create_index_if_not_exists(op.f('ix_ai_helper_sessions_last_activity_at'), 'ai_helper_sessions', ['last_activity_at'], unique=False)
    create_index_if_not_exists(op.f('ix_ai_helper_sessions_status'), 'ai_helper_sessions', ['status'], unique=False)
    create_index_if_not_exists(op.f('ix_ai_helper_sessions_user_id'), 'ai_helper_sessions', ['user_id'], unique=False)
    op.alter_column('application_profiles', 'architecture_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               nullable=True)
    op.alter_column('application_profiles', 'service_mappings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               nullable=True)
    op.alter_column('application_profiles', 'default_metrics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               nullable=True)
    op.alter_column('application_profiles', 'slos',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               nullable=True)
    op.alter_column('application_profiles', 'default_time_range',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=True)
    op.alter_column('application_profiles', 'log_patterns',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               nullable=True)
    op.alter_column('application_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.alter_column('application_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    drop_index_if_exists('idx_design_chunks_knowledge_source', table_name='design_chunks')
    drop_constraint_if_exists('design_chunks_knowledge_source_id_fkey', 'design_chunks', type_='foreignkey')
    drop_column_if_exists('design_chunks', 'knowledge_source_id')
    drop_index_if_exists('idx_design_documents_source', table_name='design_documents')
    drop_constraint_if_exists('design_documents_source_id_fkey', 'design_documents', type_='foreignkey')
    drop_column_if_exists('design_documents', 'source_id')
    op.alter_column('grafana_datasources', 'auth_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=True)
    op.alter_column('grafana_datasources', 'timeout',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('grafana_datasources', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('grafana_datasources', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('grafana_datasources', 'config_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               nullable=True)
    op.alter_column('grafana_datasources', 'custom_headers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               nullable=True)
    op.alter_column('grafana_datasources', 'is_healthy',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('grafana_datasources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.alter_column('grafana_datasources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    drop_index_if_exists('idx_incident_metrics_assigned_to', table_name='incident_metrics')
    op.alter_column('inquiry_results', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('inquiry_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    drop_index_if_exists('ix_inquiry_results_created_at', table_name='inquiry_results')
    drop_index_if_exists('ix_inquiry_results_session_id', table_name='inquiry_results')
    drop_index_if_exists('ix_inquiry_results_user_id', table_name='inquiry_results')
    op.alter_column('inquiry_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('inquiry_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.alter_column('inquiry_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    drop_index_if_exists('ix_inquiry_sessions_updated_at', table_name='inquiry_sessions')
    drop_index_if_exists('ix_inquiry_sessions_user_id', table_name='inquiry_sessions')
    op.alter_column('knowledge_sources', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('knowledge_sources', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('knowledge_sources', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'auto_sync',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'last_sync_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'sync_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'total_documents',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'total_chunks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    drop_index_if_exists('idx_knowledge_sources_enabled', table_name='knowledge_sources', postgresql_where='(enabled = true)')
    drop_index_if_exists('idx_knowledge_sources_status', table_name='knowledge_sources')
    drop_index_if_exists('idx_knowledge_sources_tenant', table_name='knowledge_sources')
    drop_index_if_exists('idx_knowledge_sources_type', table_name='knowledge_sources')
    drop_constraint_if_exists('unique_source_name_per_tenant', 'knowledge_sources', type_='unique')
    create_index_if_not_exists(op.f('ix_knowledge_sources_enabled'), 'knowledge_sources', ['enabled'], unique=False)
    create_index_if_not_exists(op.f('ix_knowledge_sources_source_type'), 'knowledge_sources', ['source_type'], unique=False)
    create_index_if_not_exists(op.f('ix_knowledge_sources_status'), 'knowledge_sources', ['status'], unique=False)
    create_index_if_not_exists(op.f('ix_knowledge_sources_tenant_id'), 'knowledge_sources', ['tenant_id'], unique=False)
    op.alter_column('knowledge_sync_history', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('knowledge_sync_history', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('knowledge_sync_history', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('knowledge_sync_history', 'documents_added',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('knowledge_sync_history', 'documents_updated',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('knowledge_sync_history', 'documents_deleted',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('knowledge_sync_history', 'chunks_created',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('knowledge_sync_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    drop_index_if_exists('idx_sync_history_created', table_name='knowledge_sync_history')
    drop_index_if_exists('idx_sync_history_source', table_name='knowledge_sync_history')
    drop_index_if_exists('idx_sync_history_status', table_name='knowledge_sync_history')
    create_index_if_not_exists(op.f('ix_knowledge_sync_history_source_id'), 'knowledge_sync_history', ['source_id'], unique=False)
    op.alter_column('runbook_clicks', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('runbook_clicks', 'source',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('runbook_clicks', 'clicked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    drop_index_if_exists('idx_runbook_clicks_session_id', table_name='runbook_clicks')
    create_index_if_not_exists(op.f('ix_runbook_clicks_clicked_at'), 'runbook_clicks', ['clicked_at'], unique=False)
    create_index_if_not_exists(op.f('ix_runbook_clicks_runbook_id'), 'runbook_clicks', ['runbook_id'], unique=False)
    create_index_if_not_exists(op.f('ix_runbook_clicks_session_id'), 'runbook_clicks', ['session_id'], unique=False)
    create_index_if_not_exists(op.f('ix_runbook_clicks_user_id'), 'runbook_clicks', ['user_id'], unique=False)
    drop_index_if_exists('idx_runbooks_embedding', table_name='runbooks', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    create_index_if_not_exists('idx_runbooks_embedding', 'runbooks', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    drop_index_if_exists(op.f('ix_runbook_clicks_user_id'), table_name='runbook_clicks')
    drop_index_if_exists(op.f('ix_runbook_clicks_session_id'), table_name='runbook_clicks')
    drop_index_if_exists(op.f('ix_runbook_clicks_runbook_id'), table_name='runbook_clicks')
    drop_index_if_exists(op.f('ix_runbook_clicks_clicked_at'), table_name='runbook_clicks')
    create_index_if_not_exists('idx_runbook_clicks_session_id', 'runbook_clicks', ['session_id'], unique=False)
    op.alter_column('runbook_clicks', 'clicked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('runbook_clicks', 'source',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'unknown'::character varying"),
               existing_nullable=False)
    op.alter_column('runbook_clicks', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    drop_index_if_exists(op.f('ix_knowledge_sync_history_source_id'), table_name='knowledge_sync_history')
    create_index_if_not_exists('idx_sync_history_status', 'knowledge_sync_history', ['status'], unique=False)
    create_index_if_not_exists('idx_sync_history_source', 'knowledge_sync_history', ['source_id'], unique=False)
    create_index_if_not_exists('idx_sync_history_created', 'knowledge_sync_history', [sa.text('created_at DESC')], unique=False)
    op.alter_column('knowledge_sync_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('knowledge_sync_history', 'chunks_created',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('knowledge_sync_history', 'documents_deleted',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('knowledge_sync_history', 'documents_updated',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('knowledge_sync_history', 'documents_added',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('knowledge_sync_history', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'running'::character varying"),
               existing_nullable=False)
    op.alter_column('knowledge_sync_history', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('knowledge_sync_history', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    drop_index_if_exists(op.f('ix_knowledge_sources_tenant_id'), table_name='knowledge_sources')
    drop_index_if_exists(op.f('ix_knowledge_sources_status'), table_name='knowledge_sources')
    drop_index_if_exists(op.f('ix_knowledge_sources_source_type'), table_name='knowledge_sources')
    drop_index_if_exists(op.f('ix_knowledge_sources_enabled'), table_name='knowledge_sources')
    op.create_unique_constraint('unique_source_name_per_tenant', 'knowledge_sources', ['tenant_id', 'name'])
    create_index_if_not_exists('idx_knowledge_sources_type', 'knowledge_sources', ['source_type'], unique=False)
    create_index_if_not_exists('idx_knowledge_sources_tenant', 'knowledge_sources', ['tenant_id'], unique=False)
    create_index_if_not_exists('idx_knowledge_sources_status', 'knowledge_sources', ['status'], unique=False)
    create_index_if_not_exists('idx_knowledge_sources_enabled', 'knowledge_sources', ['enabled'], unique=False, postgresql_where='(enabled = true)')
    op.alter_column('knowledge_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'total_chunks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'total_documents',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'sync_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'last_sync_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'auto_sync',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('knowledge_sources', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    create_index_if_not_exists('ix_inquiry_sessions_user_id', 'inquiry_sessions', ['user_id'], unique=False)
    create_index_if_not_exists('ix_inquiry_sessions_updated_at', 'inquiry_sessions', ['updated_at'], unique=False)
    op.alter_column('inquiry_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('inquiry_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('inquiry_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    create_index_if_not_exists('ix_inquiry_results_user_id', 'inquiry_results', ['user_id'], unique=False)
    create_index_if_not_exists('ix_inquiry_results_session_id', 'inquiry_results', ['session_id'], unique=False)
    create_index_if_not_exists('ix_inquiry_results_created_at', 'inquiry_results', ['created_at'], unique=False)
    op.alter_column('inquiry_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('inquiry_results', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    create_index_if_not_exists('idx_incident_metrics_assigned_to', 'incident_metrics', ['assigned_to'], unique=False)
    op.alter_column('grafana_datasources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('grafana_datasources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('grafana_datasources', 'is_healthy',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('grafana_datasources', 'custom_headers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               nullable=False)
    op.alter_column('grafana_datasources', 'config_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               nullable=False)
    op.alter_column('grafana_datasources', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('grafana_datasources', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('grafana_datasources', 'timeout',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               nullable=False)
    op.alter_column('grafana_datasources', 'auth_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'none'::character varying"),
               nullable=False)
    add_column_if_not_exists('design_documents', sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('design_documents_source_id_fkey', 'design_documents', 'knowledge_sources', ['source_id'], ['id'], ondelete='SET NULL')
    create_index_if_not_exists('idx_design_documents_source', 'design_documents', ['source_id'], unique=False)
    add_column_if_not_exists('design_chunks', sa.Column('knowledge_source_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('design_chunks_knowledge_source_id_fkey', 'design_chunks', 'knowledge_sources', ['knowledge_source_id'], ['id'], ondelete='SET NULL')
    create_index_if_not_exists('idx_design_chunks_knowledge_source', 'design_chunks', ['knowledge_source_id'], unique=False)
    op.alter_column('application_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('application_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('application_profiles', 'log_patterns',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               nullable=False)
    op.alter_column('application_profiles', 'default_time_range',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'1h'::character varying"),
               nullable=False)
    op.alter_column('application_profiles', 'slos',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               nullable=False)
    op.alter_column('application_profiles', 'default_metrics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               nullable=False)
    op.alter_column('application_profiles', 'service_mappings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               nullable=False)
    op.alter_column('application_profiles', 'architecture_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               nullable=False)
    drop_index_if_exists(op.f('ix_ai_helper_sessions_user_id'), table_name='ai_helper_sessions')
    drop_index_if_exists(op.f('ix_ai_helper_sessions_status'), table_name='ai_helper_sessions')
    drop_index_if_exists(op.f('ix_ai_helper_sessions_last_activity_at'), table_name='ai_helper_sessions')
    create_index_if_not_exists('idx_ai_sessions_user', 'ai_helper_sessions', ['user_id'], unique=False)
    create_index_if_not_exists('idx_ai_sessions_status', 'ai_helper_sessions', ['status'], unique=False)
    create_index_if_not_exists('idx_ai_sessions_activity', 'ai_helper_sessions', [sa.text('last_activity_at DESC')], unique=False)
    op.alter_column('ai_helper_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('ai_helper_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('ai_helper_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('ai_helper_sessions', 'total_cost_usd',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('ai_helper_sessions', 'total_tokens_used',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('ai_helper_sessions', 'total_queries',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('ai_helper_sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=True)
    op.alter_column('ai_helper_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'general'::character varying"),
               existing_nullable=True)
    op.alter_column('ai_helper_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    drop_index_if_exists(op.f('ix_ai_helper_config_config_type'), table_name='ai_helper_config')
    drop_index_if_exists(op.f('ix_ai_helper_config_config_key'), table_name='ai_helper_config')
    create_index_if_not_exists('idx_ai_config_type', 'ai_helper_config', ['config_type'], unique=False)
    create_index_if_not_exists('idx_ai_config_key', 'ai_helper_config', ['config_key'], unique=False)
    op.create_unique_constraint('ai_helper_config_config_key_key', 'ai_helper_config', ['config_key'])
    op.alter_column('ai_helper_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('ai_helper_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('ai_helper_config', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('ai_helper_config', 'is_encrypted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('ai_helper_config', 'config_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'system'::character varying"),
               existing_nullable=True)
    op.alter_column('ai_helper_config', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    drop_constraint_if_exists(None, 'ai_helper_audit_logs', type_='foreignkey')
    drop_index_if_exists(op.f('ix_ai_helper_audit_logs_user_id'), table_name='ai_helper_audit_logs')
    drop_index_if_exists(op.f('ix_ai_helper_audit_logs_user_action'), table_name='ai_helper_audit_logs')
    drop_index_if_exists(op.f('ix_ai_helper_audit_logs_timestamp'), table_name='ai_helper_audit_logs')
    drop_index_if_exists(op.f('ix_ai_helper_audit_logs_session_id'), table_name='ai_helper_audit_logs')
    drop_index_if_exists(op.f('ix_ai_helper_audit_logs_is_error'), table_name='ai_helper_audit_logs')
    drop_index_if_exists(op.f('ix_ai_helper_audit_logs_execution_result'), table_name='ai_helper_audit_logs')
    drop_index_if_exists(op.f('ix_ai_helper_audit_logs_executed'), table_name='ai_helper_audit_logs')
    drop_index_if_exists(op.f('ix_ai_helper_audit_logs_correlation_id'), table_name='ai_helper_audit_logs')
    drop_index_if_exists(op.f('ix_ai_helper_audit_logs_ai_suggested_action'), table_name='ai_helper_audit_logs')
    drop_index_if_exists(op.f('ix_ai_helper_audit_logs_action_blocked'), table_name='ai_helper_audit_logs')
    create_index_if_not_exists('idx_ai_audit_user_time', 'ai_helper_audit_logs', ['user_id', sa.text('timestamp DESC')], unique=False)
    create_index_if_not_exists('idx_ai_audit_user_action', 'ai_helper_audit_logs', ['user_action'], unique=False)
    create_index_if_not_exists('idx_ai_audit_timestamp', 'ai_helper_audit_logs', [sa.text('timestamp DESC')], unique=False)
    create_index_if_not_exists('idx_ai_audit_session', 'ai_helper_audit_logs', ['session_id'], unique=False)
    create_index_if_not_exists('idx_ai_audit_executed', 'ai_helper_audit_logs', ['executed', 'execution_result'], unique=False)
    create_index_if_not_exists('idx_ai_audit_error', 'ai_helper_audit_logs', ['is_error'], unique=False, postgresql_where='(is_error = true)')
    create_index_if_not_exists('idx_ai_audit_correlation', 'ai_helper_audit_logs', ['correlation_id'], unique=False)
    create_index_if_not_exists('idx_ai_audit_blocked', 'ai_helper_audit_logs', ['action_blocked'], unique=False, postgresql_where='(action_blocked = true)')
    create_index_if_not_exists('idx_ai_audit_action', 'ai_helper_audit_logs', ['ai_suggested_action'], unique=False)
    op.alter_column('ai_helper_audit_logs', 'is_error',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('ai_helper_audit_logs', 'permission_checked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('ai_helper_audit_logs', 'action_blocked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('ai_helper_audit_logs', 'executed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('ai_helper_audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('ai_helper_audit_logs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    drop_index_if_exists(op.f('ix_ai_feedback_user_id'), table_name='ai_feedback')
    drop_index_if_exists(op.f('ix_ai_feedback_session_id'), table_name='ai_feedback')
    drop_index_if_exists(op.f('ix_ai_feedback_runbook_id'), table_name='ai_feedback')
    drop_index_if_exists(op.f('ix_ai_feedback_message_id'), table_name='ai_feedback')
    drop_index_if_exists(op.f('ix_ai_feedback_created_at'), table_name='ai_feedback')
    op.create_index('idx_ai_feedback_session_id', 'ai_feedback', ['session_id'], unique=False)
    op.create_index('idx_ai_feedback_message_id', 'ai_feedback', ['message_id'], unique=False)
    op.alter_column('ai_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('ai_feedback', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
