"""add_conditional_step_fields

Revision ID: 942d381be0b3
Revises: 032
Create Date: 2025-12-25 11:38:58.825416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '942d381be0b3'
down_revision = '032'
branch_labels = None
depends_on = None



def create_index_safe(index_name, table_name, columns, **kw):
    conn = op.get_bind()
    # Check if index exists using sqlalchemy text
    # Note: sa.text is available because 'import sqlalchemy as sa' is in the file
    res = conn.execute(sa.text(f"SELECT 1 FROM pg_indexes WHERE indexname = '{index_name}'"))
    if not res.scalar():
        op.create_index(index_name, table_name, columns, **kw)

def drop_index_safe(index_name, table_name, **kw):
    conn = op.get_bind()
    res = conn.execute(sa.text(f"SELECT 1 FROM pg_indexes WHERE indexname = '{index_name}'"))
    if res.scalar():
        op.drop_index(index_name, table_name=table_name, **kw)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    drop_index_safe('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('agent_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('agent_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('ix_agent_sessions_chat_session_id', table_name='agent_sessions')
    drop_index_safe('ix_agent_sessions_status', table_name='agent_sessions')
    drop_index_safe('ix_agent_sessions_user_id', table_name='agent_sessions')
    op.alter_column('agent_steps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('ix_agent_steps_agent_session_id', table_name='agent_steps')
    drop_index_safe('ix_agent_steps_step_number', table_name='agent_steps')
    op.drop_constraint('agent_steps_agent_session_id_fkey', 'agent_steps', type_='foreignkey')
    op.create_foreign_key(None, 'agent_steps', 'agent_sessions', ['agent_session_id'], ['id'])
    op.alter_column('alert_clusters', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alert_clusters', 'alert_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alert_clusters', 'cluster_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alert_clusters', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alert_clusters', 'cluster_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('alert_clusters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('alert_clusters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('alert_clusters_cluster_key_key', 'alert_clusters', type_='unique')
    drop_index_safe('idx_cluster_active', table_name='alert_clusters')
    drop_index_safe('idx_cluster_first_seen', table_name='alert_clusters')
    drop_index_safe('idx_cluster_key', table_name='alert_clusters')
    drop_index_safe('idx_cluster_last_seen', table_name='alert_clusters')
    drop_index_safe('idx_cluster_severity', table_name='alert_clusters')
    create_index_safe(op.f('ix_alert_clusters_cluster_key'), 'alert_clusters', ['cluster_key'], unique=True)
    create_index_safe(op.f('ix_alert_clusters_first_seen'), 'alert_clusters', ['first_seen'], unique=False)
    create_index_safe(op.f('ix_alert_clusters_is_active'), 'alert_clusters', ['is_active'], unique=False)
    create_index_safe(op.f('ix_alert_clusters_last_seen'), 'alert_clusters', ['last_seen'], unique=False)
    create_index_safe(op.f('ix_alert_clusters_severity'), 'alert_clusters', ['severity'], unique=False)
    op.alter_column('alert_correlations', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alert_correlations', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alert_correlations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('alert_correlations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('alerts_embedding_idx', table_name='alerts', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    drop_index_safe('idx_alert_cluster', table_name='alerts')
    drop_index_safe('idx_alerts_correlation_id', table_name='alerts')
    create_index_safe(op.f('ix_alerts_cluster_id'), 'alerts', ['cluster_id'], unique=False)
    create_index_safe(op.f('ix_alerts_correlation_id'), 'alerts', ['correlation_id'], unique=False)
    op.alter_column('analysis_feedback', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analysis_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('application_components', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('application_components', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('application_components', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('uq_app_component_name', 'application_components', type_='unique')
    op.alter_column('applications', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    create_index_safe(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    create_index_safe(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    create_index_safe('idx_blackout_enabled', 'blackout_windows', ['enabled'], unique=False)
    create_index_safe(op.f('ix_blackout_windows_enabled'), 'blackout_windows', ['enabled'], unique=False)
    op.alter_column('change_events', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('change_events', 'associated_cis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('change_events', 'change_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('change_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('change_events_change_id_key', 'change_events', type_='unique')
    drop_index_safe('idx_change_correlation', table_name='change_events')
    drop_index_safe('idx_change_id', table_name='change_events')
    drop_index_safe('idx_change_service', table_name='change_events')
    drop_index_safe('idx_change_source', table_name='change_events')
    drop_index_safe('idx_change_timestamp', table_name='change_events')
    create_index_safe(op.f('ix_change_events_change_id'), 'change_events', ['change_id'], unique=True)
    create_index_safe(op.f('ix_change_events_correlation_score'), 'change_events', ['correlation_score'], unique=False)
    create_index_safe(op.f('ix_change_events_service_name'), 'change_events', ['service_name'], unique=False)
    create_index_safe(op.f('ix_change_events_source'), 'change_events', ['source'], unique=False)
    create_index_safe(op.f('ix_change_events_timestamp'), 'change_events', ['timestamp'], unique=False)
    op.alter_column('change_impact_analysis', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('change_impact_analysis', 'incidents_after',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('change_impact_analysis', 'critical_incidents',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('change_impact_analysis', 'analyzed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('idx_impact_change', table_name='change_impact_analysis')
    drop_index_safe('idx_impact_score', table_name='change_impact_analysis')
    create_index_safe(op.f('ix_change_impact_analysis_correlation_score'), 'change_impact_analysis', ['correlation_score'], unique=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    create_index_safe('idx_circuit_breaker_state', 'circuit_breakers', ['state'], unique=False)
    create_index_safe('idx_allowlist_enabled_os', 'command_allowlist', ['enabled', 'os_type'], unique=False)
    create_index_safe('idx_blocklist_enabled_os', 'command_blocklist', ['enabled', 'os_type'], unique=False)
    op.alter_column('component_dependencies', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('component_dependencies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('uq_component_dependency', 'component_dependencies', type_='unique')
    op.alter_column('dashboard_annotations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dashboard_annotations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('ix_dashboard_annotations_dashboard_id', table_name='dashboard_annotations')
    op.alter_column('dashboard_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dashboard_links', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('ix_dashboard_links_dashboard_id', table_name='dashboard_links')
    drop_index_safe('ix_dashboard_panels_dashboard', table_name='dashboard_panels')
    drop_index_safe('ix_dashboard_panels_panel', table_name='dashboard_panels')
    op.drop_constraint('dashboard_panels_panel_id_fkey', 'dashboard_panels', type_='foreignkey')
    op.drop_constraint('dashboard_panels_dashboard_id_fkey', 'dashboard_panels', type_='foreignkey')
    op.create_foreign_key(None, 'dashboard_panels', 'prometheus_panels', ['panel_id'], ['id'])
    op.create_foreign_key(None, 'dashboard_panels', 'dashboards', ['dashboard_id'], ['id'])
    op.alter_column('dashboard_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('ix_dashboard_permissions_dashboard_id', table_name='dashboard_permissions')
    drop_index_safe('ix_dashboard_permissions_role', table_name='dashboard_permissions')
    drop_index_safe('ix_dashboard_permissions_user_id', table_name='dashboard_permissions')
    op.drop_constraint('dashboard_permissions_dashboard_id_fkey', 'dashboard_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'dashboard_permissions', 'dashboards', ['dashboard_id'], ['id'])
    op.alter_column('dashboard_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('dashboard_snapshots_key_key', 'dashboard_snapshots', type_='unique')
    drop_index_safe('ix_dashboard_snapshots_dashboard_id', table_name='dashboard_snapshots')
    drop_index_safe('ix_dashboard_snapshots_key', table_name='dashboard_snapshots')
    create_index_safe(op.f('ix_dashboard_snapshots_key'), 'dashboard_snapshots', ['key'], unique=True)
    op.alter_column('dashboard_variables', 'depends_on',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('dashboard_variables', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dashboard_variables', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('ix_dashboard_variables_dashboard_id', table_name='dashboard_variables')
    op.alter_column('dashboards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dashboards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('design_chunks', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('design_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('design_chunks_embedding_idx', table_name='design_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('design_documents', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('design_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('design_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('design_images', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('design_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('execution_outcomes', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('execution_outcomes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    create_index_safe('idx_rate_limit_scope_window', 'execution_rate_limits', ['scope', 'scope_id', 'window_start'], unique=False)
    op.alter_column('failure_patterns', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('failure_patterns', 'occurrence_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('failure_patterns', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('failure_patterns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('idx_failure_patterns_root_cause', table_name='failure_patterns')
    create_index_safe(op.f('ix_failure_patterns_root_cause_type'), 'failure_patterns', ['root_cause_type'], unique=False)
    op.alter_column('group_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('incident_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('incident_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('idx_metrics_alert', table_name='incident_metrics')
    drop_index_safe('idx_metrics_resolution', table_name='incident_metrics')
    drop_index_safe('idx_metrics_resolved', table_name='incident_metrics')
    drop_index_safe('idx_metrics_service', table_name='incident_metrics')
    drop_index_safe('idx_metrics_severity', table_name='incident_metrics')
    create_index_safe(op.f('ix_incident_metrics_resolution_type'), 'incident_metrics', ['resolution_type'], unique=False)
    create_index_safe(op.f('ix_incident_metrics_service_name'), 'incident_metrics', ['service_name'], unique=False)
    create_index_safe(op.f('ix_incident_metrics_severity'), 'incident_metrics', ['severity'], unique=False)
    op.alter_column('itsm_integrations', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('itsm_integrations', 'connector_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('itsm_integrations', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('itsm_integrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('itsm_integrations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('idx_itsm_enabled', table_name='itsm_integrations')
    drop_index_safe('idx_itsm_last_sync', table_name='itsm_integrations')
    create_index_safe(op.f('ix_itsm_integrations_is_enabled'), 'itsm_integrations', ['is_enabled'], unique=False)
    create_index_safe(op.f('ix_itsm_integrations_last_sync'), 'itsm_integrations', ['last_sync'], unique=False)
    op.alter_column('panel_rows', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('panel_rows', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('ix_panel_rows_dashboard_id', table_name='panel_rows')
    drop_index_safe('ix_playlist_items_playlist_id', table_name='playlist_items')
    op.alter_column('playlists', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('playlists', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('prometheus_datasources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('prometheus_datasources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('prometheus_panels', 'panel_type',
               existing_type=postgresql.ENUM('graph', 'gauge', 'stat', 'table', 'heatmap', 'bar', 'pie', name='paneltype'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('prometheus_panels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('prometheus_panels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('ix_prometheus_panels_datasource', table_name='prometheus_panels')
    op.alter_column('query_history', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('query_history', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('query_history', 'executed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('ix_query_history_dashboard_id', table_name='query_history')
    drop_index_safe('ix_query_history_executed_by', table_name='query_history')
    op.alter_column('runbook_acls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('runbook_acls', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    create_index_safe('idx_executions_alert', 'runbook_executions', ['alert_id'], unique=False)
    create_index_safe('idx_executions_approval_token', 'runbook_executions', ['approval_token'], unique=False)
    create_index_safe('idx_executions_queued_at', 'runbook_executions', ['queued_at'], unique=False)
    create_index_safe('idx_executions_runbook_status', 'runbook_executions', ['runbook_id', 'status'], unique=False)
    create_index_safe('idx_executions_status', 'runbook_executions', ['status'], unique=False)
    op.add_column('runbook_steps', sa.Column('run_if_variable', sa.String(length=100), nullable=True))
    op.add_column('runbook_steps', sa.Column('run_if_value', sa.String(length=500), nullable=True))
    create_index_safe('idx_runbook_steps_type', 'runbook_steps', ['step_type'], unique=False)
    create_index_safe('idx_triggers_alert_name', 'runbook_triggers', ['alert_name_pattern'], unique=False)
    create_index_safe('idx_triggers_enabled_priority', 'runbook_triggers', ['enabled', 'priority'], unique=False)
    create_index_safe('idx_runbooks_category', 'runbooks', ['category'], unique=False)
    create_index_safe('idx_runbooks_enabled_auto', 'runbooks', ['enabled', 'auto_execute'], unique=False)
    op.alter_column('schedule_execution_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('idx_schedule_history_created', table_name='schedule_execution_history')
    drop_index_safe('idx_schedule_history_job', table_name='schedule_execution_history')
    drop_index_safe('idx_schedule_history_status', table_name='schedule_execution_history')
    op.alter_column('scheduled_jobs', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'max_instances',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'misfire_grace_time',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'run_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'failure_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    drop_index_safe('idx_scheduled_jobs_enabled', table_name='scheduled_jobs', postgresql_where='(enabled = true)')
    drop_index_safe('idx_scheduled_jobs_next_run', table_name='scheduled_jobs', postgresql_where='(enabled = true)')
    drop_index_safe('idx_scheduled_jobs_runbook', table_name='scheduled_jobs')
    create_index_safe(op.f('ix_server_groups_parent_id'), 'server_groups', ['parent_id'], unique=False)
    create_index_safe('idx_step_executions_execution_id', 'step_executions', ['execution_id'], unique=False)
    create_index_safe('idx_step_executions_status', 'step_executions', ['status'], unique=False)
    create_index_safe(op.f('ix_terminal_sessions_started_at'), 'terminal_sessions', ['started_at'], unique=False)
    create_index_safe(op.f('ix_terminal_sessions_user_id'), 'terminal_sessions', ['user_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.create_foreign_key(None, 'users', 'llm_providers', ['default_llm_provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    drop_index_safe(op.f('ix_terminal_sessions_user_id'), table_name='terminal_sessions')
    drop_index_safe(op.f('ix_terminal_sessions_started_at'), table_name='terminal_sessions')
    drop_index_safe('idx_step_executions_status', table_name='step_executions')
    drop_index_safe('idx_step_executions_execution_id', table_name='step_executions')
    drop_index_safe(op.f('ix_server_groups_parent_id'), table_name='server_groups')
    create_index_safe('idx_scheduled_jobs_runbook', 'scheduled_jobs', ['runbook_id'], unique=False)
    create_index_safe('idx_scheduled_jobs_next_run', 'scheduled_jobs', ['next_run_at'], unique=False, postgresql_where='(enabled = true)')
    create_index_safe('idx_scheduled_jobs_enabled', 'scheduled_jobs', ['enabled'], unique=False, postgresql_where='(enabled = true)')
    op.alter_column('scheduled_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'failure_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'run_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'misfire_grace_time',
               existing_type=sa.INTEGER(),
               server_default=sa.text('300'),
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'max_instances',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'UTC'::character varying"),
               existing_nullable=True)
    create_index_safe('idx_schedule_history_status', 'schedule_execution_history', ['status'], unique=False)
    create_index_safe('idx_schedule_history_job', 'schedule_execution_history', ['scheduled_job_id'], unique=False)
    create_index_safe('idx_schedule_history_created', 'schedule_execution_history', ['created_at'], unique=False)
    op.alter_column('schedule_execution_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    drop_index_safe('idx_runbooks_enabled_auto', table_name='runbooks')
    drop_index_safe('idx_runbooks_category', table_name='runbooks')
    drop_index_safe('idx_triggers_enabled_priority', table_name='runbook_triggers')
    drop_index_safe('idx_triggers_alert_name', table_name='runbook_triggers')
    drop_index_safe('idx_runbook_steps_type', table_name='runbook_steps')
    op.drop_column('runbook_steps', 'run_if_value')
    op.drop_column('runbook_steps', 'run_if_variable')
    drop_index_safe('idx_executions_status', table_name='runbook_executions')
    drop_index_safe('idx_executions_runbook_status', table_name='runbook_executions')
    drop_index_safe('idx_executions_queued_at', table_name='runbook_executions')
    drop_index_safe('idx_executions_approval_token', table_name='runbook_executions')
    drop_index_safe('idx_executions_alert', table_name='runbook_executions')
    op.alter_column('runbook_acls', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('runbook_acls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    create_index_safe('ix_query_history_executed_by', 'query_history', ['executed_by'], unique=False)
    create_index_safe('ix_query_history_dashboard_id', 'query_history', ['dashboard_id'], unique=False)
    op.alter_column('query_history', 'executed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('query_history', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('query_history', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'success'::character varying"),
               existing_nullable=True)
    create_index_safe('ix_prometheus_panels_datasource', 'prometheus_panels', ['datasource_id'], unique=False)
    op.alter_column('prometheus_panels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('prometheus_panels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('prometheus_panels', 'panel_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('graph', 'gauge', 'stat', 'table', 'heatmap', 'bar', 'pie', name='paneltype'),
               existing_nullable=True)
    op.alter_column('prometheus_datasources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('prometheus_datasources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('playlists', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('playlists', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    create_index_safe('ix_playlist_items_playlist_id', 'playlist_items', ['playlist_id'], unique=False)
    create_index_safe('ix_panel_rows_dashboard_id', 'panel_rows', ['dashboard_id'], unique=False)
    op.alter_column('panel_rows', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('panel_rows', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    drop_index_safe(op.f('ix_itsm_integrations_last_sync'), table_name='itsm_integrations')
    drop_index_safe(op.f('ix_itsm_integrations_is_enabled'), table_name='itsm_integrations')
    create_index_safe('idx_itsm_last_sync', 'itsm_integrations', ['last_sync'], unique=False)
    create_index_safe('idx_itsm_enabled', 'itsm_integrations', ['is_enabled'], unique=False)
    op.alter_column('itsm_integrations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('itsm_integrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('itsm_integrations', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('itsm_integrations', 'connector_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'generic_api'::character varying"),
               existing_nullable=False)
    op.alter_column('itsm_integrations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    drop_index_safe(op.f('ix_incident_metrics_severity'), table_name='incident_metrics')
    drop_index_safe(op.f('ix_incident_metrics_service_name'), table_name='incident_metrics')
    drop_index_safe(op.f('ix_incident_metrics_resolution_type'), table_name='incident_metrics')
    create_index_safe('idx_metrics_severity', 'incident_metrics', ['severity'], unique=False)
    create_index_safe('idx_metrics_service', 'incident_metrics', ['service_name'], unique=False)
    create_index_safe('idx_metrics_resolved', 'incident_metrics', ['incident_resolved'], unique=False)
    create_index_safe('idx_metrics_resolution', 'incident_metrics', ['resolution_type'], unique=False)
    create_index_safe('idx_metrics_alert', 'incident_metrics', ['alert_id'], unique=False)
    op.alter_column('incident_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('incident_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('group_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    drop_index_safe(op.f('ix_failure_patterns_root_cause_type'), table_name='failure_patterns')
    create_index_safe('idx_failure_patterns_root_cause', 'failure_patterns', ['root_cause_type'], unique=False)
    op.alter_column('failure_patterns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('failure_patterns', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('failure_patterns', 'occurrence_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('failure_patterns', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    drop_index_safe('idx_rate_limit_scope_window', table_name='execution_rate_limits')
    op.alter_column('execution_outcomes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('execution_outcomes', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('design_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('design_images', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('design_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('design_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('design_documents', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    create_index_safe('design_chunks_embedding_idx', 'design_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('design_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('design_chunks', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('dashboards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('dashboards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    create_index_safe('ix_dashboard_variables_dashboard_id', 'dashboard_variables', ['dashboard_id'], unique=False)
    op.alter_column('dashboard_variables', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('dashboard_variables', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('dashboard_variables', 'depends_on',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    drop_index_safe(op.f('ix_dashboard_snapshots_key'), table_name='dashboard_snapshots')
    create_index_safe('ix_dashboard_snapshots_key', 'dashboard_snapshots', ['key'], unique=False)
    create_index_safe('ix_dashboard_snapshots_dashboard_id', 'dashboard_snapshots', ['dashboard_id'], unique=False)
    op.create_unique_constraint('dashboard_snapshots_key_key', 'dashboard_snapshots', ['key'], postgresql_nulls_not_distinct=False)
    op.alter_column('dashboard_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_constraint(None, 'dashboard_permissions', type_='foreignkey')
    op.create_foreign_key('dashboard_permissions_dashboard_id_fkey', 'dashboard_permissions', 'dashboards', ['dashboard_id'], ['id'], ondelete='CASCADE')
    create_index_safe('ix_dashboard_permissions_user_id', 'dashboard_permissions', ['user_id'], unique=False)
    create_index_safe('ix_dashboard_permissions_role', 'dashboard_permissions', ['role'], unique=False)
    create_index_safe('ix_dashboard_permissions_dashboard_id', 'dashboard_permissions', ['dashboard_id'], unique=False)
    op.alter_column('dashboard_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_constraint(None, 'dashboard_panels', type_='foreignkey')
    op.drop_constraint(None, 'dashboard_panels', type_='foreignkey')
    op.create_foreign_key('dashboard_panels_dashboard_id_fkey', 'dashboard_panels', 'dashboards', ['dashboard_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('dashboard_panels_panel_id_fkey', 'dashboard_panels', 'prometheus_panels', ['panel_id'], ['id'], ondelete='CASCADE')
    create_index_safe('ix_dashboard_panels_panel', 'dashboard_panels', ['panel_id'], unique=False)
    create_index_safe('ix_dashboard_panels_dashboard', 'dashboard_panels', ['dashboard_id'], unique=False)
    create_index_safe('ix_dashboard_links_dashboard_id', 'dashboard_links', ['dashboard_id'], unique=False)
    op.alter_column('dashboard_links', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('dashboard_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    create_index_safe('ix_dashboard_annotations_dashboard_id', 'dashboard_annotations', ['dashboard_id'], unique=False)
    op.alter_column('dashboard_annotations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('dashboard_annotations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.create_unique_constraint('uq_component_dependency', 'component_dependencies', ['from_component_id', 'to_component_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('component_dependencies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('component_dependencies', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    drop_index_safe('idx_blocklist_enabled_os', table_name='command_blocklist')
    drop_index_safe('idx_allowlist_enabled_os', table_name='command_allowlist')
    drop_index_safe('idx_circuit_breaker_state', table_name='circuit_breakers')
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    drop_index_safe(op.f('ix_change_impact_analysis_correlation_score'), table_name='change_impact_analysis')
    create_index_safe('idx_impact_score', 'change_impact_analysis', ['correlation_score'], unique=False)
    create_index_safe('idx_impact_change', 'change_impact_analysis', ['change_event_id'], unique=False)
    op.alter_column('change_impact_analysis', 'analyzed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('change_impact_analysis', 'critical_incidents',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('change_impact_analysis', 'incidents_after',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('change_impact_analysis', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    drop_index_safe(op.f('ix_change_events_timestamp'), table_name='change_events')
    drop_index_safe(op.f('ix_change_events_source'), table_name='change_events')
    drop_index_safe(op.f('ix_change_events_service_name'), table_name='change_events')
    drop_index_safe(op.f('ix_change_events_correlation_score'), table_name='change_events')
    drop_index_safe(op.f('ix_change_events_change_id'), table_name='change_events')
    create_index_safe('idx_change_timestamp', 'change_events', ['timestamp'], unique=False)
    create_index_safe('idx_change_source', 'change_events', ['source'], unique=False)
    create_index_safe('idx_change_service', 'change_events', ['service_name'], unique=False)
    create_index_safe('idx_change_id', 'change_events', ['change_id'], unique=True)
    create_index_safe('idx_change_correlation', 'change_events', ['correlation_score'], unique=False)
    op.create_unique_constraint('change_events_change_id_key', 'change_events', ['change_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('change_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('change_events', 'change_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('change_events', 'associated_cis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('change_events', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    drop_index_safe(op.f('ix_blackout_windows_enabled'), table_name='blackout_windows')
    drop_index_safe('idx_blackout_enabled', table_name='blackout_windows')
    drop_index_safe(op.f('ix_audit_log_user_id'), table_name='audit_log')
    drop_index_safe(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('applications', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_unique_constraint('uq_app_component_name', 'application_components', ['app_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('application_components', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('application_components', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('application_components', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('analysis_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('analysis_feedback', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    drop_index_safe(op.f('ix_alerts_correlation_id'), table_name='alerts')
    drop_index_safe(op.f('ix_alerts_cluster_id'), table_name='alerts')
    create_index_safe('idx_alerts_correlation_id', 'alerts', ['correlation_id'], unique=False)
    create_index_safe('idx_alert_cluster', 'alerts', ['cluster_id'], unique=False)
    create_index_safe('alerts_embedding_idx', 'alerts', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('alert_correlations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('alert_correlations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('alert_correlations', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('alert_correlations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    drop_index_safe(op.f('ix_alert_clusters_severity'), table_name='alert_clusters')
    drop_index_safe(op.f('ix_alert_clusters_last_seen'), table_name='alert_clusters')
    drop_index_safe(op.f('ix_alert_clusters_is_active'), table_name='alert_clusters')
    drop_index_safe(op.f('ix_alert_clusters_first_seen'), table_name='alert_clusters')
    drop_index_safe(op.f('ix_alert_clusters_cluster_key'), table_name='alert_clusters')
    create_index_safe('idx_cluster_severity', 'alert_clusters', ['severity'], unique=False)
    create_index_safe('idx_cluster_last_seen', 'alert_clusters', ['last_seen'], unique=False)
    create_index_safe('idx_cluster_key', 'alert_clusters', ['cluster_key'], unique=True)
    create_index_safe('idx_cluster_first_seen', 'alert_clusters', ['first_seen'], unique=False)
    create_index_safe('idx_cluster_active', 'alert_clusters', ['is_active'], unique=False)
    op.create_unique_constraint('alert_clusters_cluster_key_key', 'alert_clusters', ['cluster_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('alert_clusters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('alert_clusters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('alert_clusters', 'cluster_metadata',
               existing_type=sa.JSON(),
               server_default=sa.text("'{}'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('alert_clusters', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('alert_clusters', 'cluster_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'exact'::character varying"),
               existing_nullable=False)
    op.alter_column('alert_clusters', 'alert_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('alert_clusters', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'agent_steps', type_='foreignkey')
    op.create_foreign_key('agent_steps_agent_session_id_fkey', 'agent_steps', 'agent_sessions', ['agent_session_id'], ['id'], ondelete='CASCADE')
    create_index_safe('ix_agent_steps_step_number', 'agent_steps', ['agent_session_id', 'step_number'], unique=False)
    create_index_safe('ix_agent_steps_agent_session_id', 'agent_steps', ['agent_session_id'], unique=False)
    op.alter_column('agent_steps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    create_index_safe('ix_agent_sessions_user_id', 'agent_sessions', ['user_id'], unique=False)
    create_index_safe('ix_agent_sessions_status', 'agent_sessions', ['status'], unique=False)
    create_index_safe('ix_agent_sessions_chat_session_id', 'agent_sessions', ['chat_session_id'], unique=False)
    op.alter_column('agent_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('agent_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    create_index_safe('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
