"""Add file operations tables

Revision ID: c29fb7c84bd2
Revises: e9a1c2d3e4f5
Create Date: 2026-01-16 15:54:17.070932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c29fb7c84bd2'
down_revision = 'e9a1c2d3e4f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('server_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server_credentials.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_backups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_version_id', sa.UUID(), nullable=False),
    sa.Column('backup_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_version_id'], ['file_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('agent_step_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_step_id'], ['agent_steps.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('change_set_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=True),
    sa.Column('old_content', sa.Text(), nullable=True),
    sa.Column('new_content', sa.Text(), nullable=True),
    sa.Column('diff_hunks', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['change_set_id'], ['change_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_items')
    op.drop_table('change_sets')
    op.drop_table('file_backups')
    op.drop_table('file_versions')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
