"""
Postmortem Report Models
Stores AI-generated and manually-edited post-incident reviews.
"""
import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    Column, String, Text, ForeignKey, DateTime, Index,
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship

from app.database import Base


def utc_now() -> datetime:
    """Return current UTC time as timezone-aware datetime."""
    return datetime.now(timezone.utc)


class PostmortemReport(Base):
    """
    Post-incident review / postmortem report.

    Generated by AI from incident data and supports manual editing,
    out-of-band context entries and a publish workflow.
    """

    __tablename__ = "postmortem_reports"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    title = Column(String(500), nullable=False)

    # Incident context (optional FK links)
    alert_id = Column(
        UUID(as_uuid=True), ForeignKey("alerts.id"), nullable=True, index=True
    )
    app_id = Column(
        UUID(as_uuid=True), ForeignKey("applications.id"), nullable=True, index=True
    )

    # Lifecycle
    status = Column(String(20), default="draft", nullable=False)  # draft, in_review, published

    # Incident timeline bounds
    incident_start = Column(DateTime(timezone=True), nullable=True)
    incident_end = Column(DateTime(timezone=True), nullable=True)
    severity = Column(String(20), nullable=True)

    # Content (AI-generated or manually edited)
    # [{timestamp, event, source, manual: bool}]
    timeline = Column(JSONB, default=list)
    impact_summary = Column(Text, nullable=True)
    root_cause = Column(Text, nullable=True)
    # [string]
    contributing_factors = Column(JSONB, default=list)
    # [{action, runbook_id, outcome, duration_minutes}]
    remediation_actions = Column(JSONB, default=list)
    # [{description, owner, due_date, status}]
    action_items = Column(JSONB, default=list)
    lessons_learned = Column(Text, nullable=True)
    # {mttd_minutes, mtta_minutes, mtte_minutes, mttr_minutes}
    metrics = Column(JSONB, default=dict)

    # Generation info
    generated_by = Column(String(20), default="ai")  # ai | manual

    # Manual context entries [{source, content, timestamp}]
    out_of_band_context = Column(JSONB, default=list)

    # Review
    reviewed_by = Column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=True
    )
    created_by = Column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=False
    )

    created_at = Column(DateTime(timezone=True), default=utc_now)
    updated_at = Column(DateTime(timezone=True), default=utc_now, onupdate=utc_now)

    # Relationships
    alert = relationship("Alert")
    application = relationship("Application")
    reviewer = relationship("User", foreign_keys=[reviewed_by])
    creator = relationship("User", foreign_keys=[created_by])

    __table_args__ = (
        Index("ix_postmortem_reports_alert_id", "alert_id"),
        Index("ix_postmortem_reports_app_id", "app_id"),
        Index("ix_postmortem_reports_status", "status"),
    )
